version: 1-alpha.1

releases:
  pts-global-admin:
    name: Admin Testing
    autodeploy-on: default
    chart: oci://quay.csssr.cloud/charts/pts-global-admin@~1.0.0
    slack:
      - C056AM9FMB6
    builds:
      - workflow: build-docker-image-admin.yaml
        values:
          image.tag: build-{{ .Build.RunID }}
    params:
      requestLimitMb:
        type: string
        default: 5
        description: Limit for HTTP request size in megabytes

  pts-global-admin-production:
    name: Admin Production
    base: pts-global-admin
    cluster: pts-global-production
    static-params:
      environment: production
    params:
      requestLimitMb:
        type: string
        default: 15
        description: Limit for HTTP request size in megabytes

  pts-global-admin-staging:
    name: Admin Staging
    autodeploy-on:
      push:
        - main
    cluster: pts-global-production
    static-params:
      environment: staging
      enableGithubAuth: true
    chart: oci://quay.csssr.cloud/charts/pts-global-admin@~1.0.0
    builds:
      - workflow: build-docker-image-admin.yaml
        values:
          image.tag: build-{{ .Build.RunID }}

  pts-global-frontend:
    name: Frontend Testing
    autodeploy-on: default
    chart: oci://quay.csssr.cloud/charts/pts-global-frontend@~1.0.0
    slack:
      - C056AM9FMB6
    builds:
      - workflow: build-docker-image-frontend.yaml
        values:
          image.tag: build-{{ .Build.RunID }}

  pts-global-frontend-production:
    name: Frontend Production
    base: pts-global-frontend
    cluster: pts-global-production
    static-params:
      environment: production

  pts-global-frontend-staging:
    name: Frontend Staging
    autodeploy-on:
      push:
        - main
    cluster: pts-global-production
    static-params:
      environment: staging
    chart: oci://quay.csssr.cloud/charts/pts-global-frontend@~1.0.0
    builds:
      - workflow: build-docker-image-frontend-staging.yaml
        values:
          image.tag: build-{{ .Build.RunID }}
