version: 1-alpha.1

releases:
  pts-global-admin:
    name: Admin Testing
    autodeploy-on: default
    chart: oci://quay.csssr.cloud/charts/pts-global-admin@~1.0.0
    slack:
      - C056AM9FMB6
    builds:
      - workflow: build-docker-image-admin.yaml
        values:
          image.tag: build-{{ .Build.RunID }}

  pts-global-admin-production:
    name: Admin Production
    base: pts-global-admin
    cluster: pts-global-production
    static-params:
      environment: production
      enableGithubAuth: true

  pts-global-frontend:
    name: Frontend Testing
    autodeploy-on: default
    chart: oci://quay.csssr.cloud/charts/pts-global-frontend@~1.0.0
    slack:
      - C056AM9FMB6
    builds:
      - workflow: build-docker-image-frontend.yaml
        values:
          image.tag: build-{{ .Build.RunID }}

  pts-global-frontend-production:
    name: Frontend Production
    base: pts-global-frontend
    cluster: pts-global-production
    static-params:
      environment: production
      enableGithubAuth: true
